### ISSUE TITLE
please upload geojson result example for Gracio site  

### ISSUE THREAD

**Issue by RELNO** [andredaa/city_io_to_geojson#1]

**Comment by andredaa** [comment]
https://github.com/andredaa/city_io_to_geojson/blob/2ae272d5892724ff82f071299fb2746425e08069/resulting_jsons/example_grasbrook.json

You can find one here. 
Each cell has properties for type, rotation and color. More properties could be asserted.

**Comment by RELNO** [comment]
Great thanks
